### ISSUE TITLE
3A 啊 也给我写一个吧

### ISSUE THREAD

**Issue by ice1000** [sg-first/Doge_Quotations#1]
嗯
来自kindle 客户端

**Comment by sg-first** [comment]
你有啥名言警句我给你写

**Comment by ice1000** [comment]
你写个人物说明就行了
还有那次装逼大成功你还记得吗，发上去撒
嘿嘿

**Comment by ice1000** [comment]
好像Doge和HDF比较勤快的几个人当中那么多C++那么多桌面那么多服务器就我一个app开发你不觉得我很special吗√

**Comment by ice1000** [comment]
擅长使用kindle进行安卓开发（用kindle上github然后编辑代码

**Comment by ice1000** [comment]
3A？3A？在吗在吗

**Comment by ice1000** [comment]
还有爱好使用Emacs、爱好使用Android Studio并且鄙视Eclipse
初学编程时有过安装Visual Studio安装了一整天然后发现不会用于是又卸载的惨痛经历

**Comment by ice1000** [comment]
曾经长期认为[果冻](https://github.com/sg-first/Doge_Quotations/issues/1)是女生

**Comment by sg-first** [comment]
知道真相的你眼泪掉下来
